networks:
  app-network:
    name: app-network
    driver: bridge

services:
  rabbitmq-ui-proxy:
    image: kbudde/rabbitmq-exporter:latest
    container_name: rabbitmq-ui-proxy
    environment:
      RABBIT_HOST: ${RABBITMQ_HOST:-localhost}
      RABBIT_PORT: ${RABBITMQ_PORT:-5672}
      RABBIT_USERNAME: ${RABBITMQ_USERNAME:-admin123}
      RABBIT_PASSWORD: ${RABBITMQ_PASSWORD:-admin123}
      RABBIT_VHOST: ${RABBITMQ_VHOST:-/}
      RABBIT_SECURE: ${RABBITMQ_SECURE:-false}
    ports:
      - "${RABBITMQ_UI_PORT:-15681}:15672" # Expose Management UI
    restart: unless-stopped
    networks:
      - app-network
