networks:
  app-network:
    name: app-network
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin123
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - ./.docker/rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
